version: '3.8'
services:
  db:
    image: postgres:14
    container_name: db
    restart: always

    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    



    
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      

  app:
      build: .
      command: uvicorn app.main:app --host 0.0.0.0 --port 8010
      depends_on:
        - db
      ports:
        - 8010:8010
      
    #  environment:
   #     SECRET_KEY: ${SECRET_KEY}
     
   
volumes:
   db:  
